// Register
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// Login/Logout
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

// Message request
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

// Listas
export const GET_LISTS_REQUEST = "GET_LISTS_REQUEST";
export const GET_LISTS_SUCCESS = "GET_LISTS_SUCCESS";
export const GET_LISTS_FAIL = "GET_LISTS_FAIL";

export const CREATE_LIST_REQUEST = "CREATE_LIST_REQUEST";
export const CREATE_LIST_SUCCESS = "CREATE_LIST_SUCCESS";
export const CREATE_LIST_FAIL = "CREATE_LIST_FAIL";

export const DELETE_LIST_REQUEST = "DELETE_LIST_REQUEST";
export const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS";
export const DELETE_LIST_FAIL = "DELETE_LIST_FAIL";

export const GET_LIST_REQUEST = "GET_LIST_REQUEST";
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS";
export const GET_LIST_FAIL = "GET_LIST_FAIL";

export const ADD_LIST_REQUEST = "ADD_LIST_REQUEST";
export const ADD_LIST_SUCCESS = "ADD_LIST_SUCCESS";
export const ADD_LIST_FAIL = "ADD_LIST_FAIL";

// Productos
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const CREATE_PRODUCT_REQUEST = "GET_PRODUCTS_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const CREATE_PRODUCT_FAIL = "GET_PRODUCTS_FAIL";

// Tareas
export const GET_TAREAS_REQUEST = "GET_TAREAS_REQUEST";
export const GET_TAREAS_SUCCESS = "GET_TAREAS_SUCCESS";
export const GET_TAREAS_FAIL = "GET_TAREAS_FAIL";

export const GET_TAREA_REQUEST = "GET_TAREA_REQUEST";
export const GET_TAREA_SUCCESS = "GET_TAREA_SUCCESS";
export const GET_TAREA_FAIL = "GET_TAREA_FAIL";

export const CREATE_TAREA_REQUEST = "CREATE_TAREA_REQUEST";
export const CREATE_TAREA_SUCCESS = "CREATE_TAREA_SUCCESS";
export const CREATE_TAREA_FAIL = "CREATE_TAREA_FAIL";

export const SAVE_TAREA_REQUEST = "SAVE_TAREA_REQUEST";
export const SAVE_TAREA_SUCCESS = "SAVE_TAREA_SUCCESS";
export const SAVE_TAREA_FAIL = "SAVE_TAREA_FAIL";

export const DELETE_TAREA_REQUEST = "DELETE_TAREA_REQUEST";
export const DELETE_TAREA_SUCCESS = "DELETE_TAREA_SUCCESS";
export const DELETE_TAREA_FAIL = "DELETE_TAREA_FAIL";

// Users & Tareas
export const GET_USER_TAREAS_REQUEST = "GET_USER_TAREAS_REQUEST";
export const GET_USER_TAREAS_SUCCESS = "GET_USER_TAREAS_SUCCESS";
export const GET_USER_TAREAS_FAIL = "GET_USER_TAREAS_FAIL";

// Users
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";